#!/bin/bash

mv "/tmp/es_launch_dosbox" "/media/project_eris/opt/emulationstation/bin/es_launch_dosbox"

THEME_SET="$(find "/media/project_eris/opt/emulationstation/.emulationstation/es_settings.cfg" -type f | xargs grep 'ThemeSet')"
THEME_NAME="$(echo "${THEME_SET}" | cut -d '"' -f4)"
THEME_IMG="$(find /media/project_eris/opt/emulationstation/.emulationstation/themes/$THEME_NAME -name ibmpc.svg)"
[ -f "/media/project_eris/opt/emulationstation/.emulationstation/themes/$THEME_NAME/dosboxes/art/ibmpc.svg" ] && rm -f "/media/project_eris/opt/emulationstation/.emulationstation/themes/$THEME_NAME/dosboxes/art/ibmpc.svg"
cp -r -f "/media/project_eris/opt/emulationstation/.emulationstation/themes/$THEME_NAME/pc" "/media/project_eris/opt/emulationstation/.emulationstation/themes/$THEME_NAME/dosboxes"
mv "/tmp/dosboxes.svg" "$THEME_IMG"
[ ! -d "/media/roms/dosboxes" ] && mkdir -p "/media/roms/dosboxes"

if ! grep -q "DOSBox Standalone" "/media/project_eris/opt/emulationstation/.emulationstation/es_systems.cfg"; then
  sed -i '/<\/systemList>/ i\
<system>
  <name>doxboxes</name>
  <fullname>DOSBox Standalone</fullname>
  <path>/media/roms/dosboxes/</path>
  <extension>.exe .com .bat</extension>
  <command>es_launch_dosbox %ROM%</command>
  <platform>pc</platform>
  <theme>dosboxes</theme>
<\/system>\' "/media/project_eris/opt/emulationstation/.emulationstation/es_systems.cfg"
fi

[ ! -f "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI" ] && cp "/media/project_eris/etc/project_eris/CFG/project_eris_cfg_DEFAULT.INI" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"

if ! grep -q "CUSTOM GLOBAL VARIABLES" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '103i;## CUSTOM GLOBAL VARIABLES ##################################################;' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
  sed -i '105i;' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "GAME_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of games path \
GAME_PATH="${MOUNTPOINT}/games"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "ROMS_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of roms path \
ROMS_PATH="${MOUNTPOINT}/roms"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "REGION" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;System region \
REGION="$(cat "${GAADATA}/geninfo/REGION")"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "GAADATA=" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of gaadata path \
GAADATA="/gaadata"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "VOLATILE=" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of volatile path \
VOLATILE="/var/volatile"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "ES_CFG_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of Emulationstation configuration files \
ES_CFG_PATH="${PROJECT_ERIS_PATH}/opt/emulationstation/.emulationstation"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "EMULATIONSTATION_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of Emulationstation \
EMULATIONSTATION_PATH="${PROJECT_ERIS_PATH}/opt/emulationstation"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "SUPLEMENTARY_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of sound files \
SUPLEMENTARY_PATH="${PROJECT_ERIS_PATH}/etc/project_eris/SUP"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
if ! grep -q "PROJECT_ERIS_ROOT_PATH" "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"; then
  sed -i '106i;Location of Project Eris root \
PROJECT_ERIS_ROOT_PATH="${PROJECT_ERIS_PATH}/etc/project_eris"' "/media/project_eris/etc/project_eris/CFG/project_eris_cfg.INI"
fi
