#!/bin/bash
#
#  Copyright (c) 2020 DNA64 (https://github.com/DNA64/DOSBoxES/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#source "/var/volatile/project_eris.cfg"
emulator="/media/project_eris/etc/project_eris/SUP/launchers/dosbox/dosbox"
config="/media/project_eris/etc/project_eris/SUP/launchers/dosbox/default.cfg"
tmp_path="/var/volatile/tmpgame"

case ${1} in
  *\ * )
  [ -L "$tmp_path" ] && unlink "$tmp_path"
  ln -s "${1%/*}" "$tmp_path"
  file_name="${1##*/}"
  no_space="$(echo -e "${file_name}" | tr -d '[:space:]')"
  ln -s "${1}" "$tmp_path/$no_space"
  gamepath="$tmp_path"
  gamename="$no_space"
   ;;
  * )
  gamepath=${1%/*}
  gamename=$(basename "$1")
  ;;
esac
executable="$gamepath/$gamename"
doslaunch="$emulator -c mount c $executable -conf $config -fullscreen -exit"

exit "$($doslaunch)"
# EOF
