#!/bin/bash
#
#  Copyright (c) 2020 DNA64 (https://github.com/DNA64/DOSBoxES/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source "/var/volatile/project_eris.cfg"

emulator="${SUPLEMENTARY_PATH}/launchers/dosbox/dosbox"
config="${SUPLEMENTARY_PATH}/launchers/dosbox/default.cfg"
tmp_path="${VOLATILE}/tmpgame"
gamename=$(basename "$1")

case ${1} in
  *\ * )
  [ -L "$tmp_path" ] && unlink "$tmp_path"
  ln -s "${1%/*}" "$tmp_path"
  gamepath="$tmp_path"
   ;;
  * )
  gamepath=${1%/*}
  ;;
esac

doslaunch="$emulator -c mount c $gamepath/$gamename -conf $config -fullscreen"

exit "$($doslaunch)"
# EOF
